# Generated by GCP Architecture Builder
# Terraform configuration for Google Cloud Platform

terraform {
  required_version = ">= 1.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
}

variable "project_id" {
  description = "The GCP project ID"
  type        = string
}

variable "region" {
  description = "The default region"
  type        = string
  default     = "us-central1"
}

provider "google" {
  project = var.project_id
  region  = var.region
}

resource "google_cloud_run_v2_service" "tatvaagroapp_webserver" {
  name     = "tatvaagroapp_webserver"
  location = "us-central1"
  project  = var.project_id

  template {
    scaling {
      min_instance_count = 0
      max_instance_count = 10
    }
    containers {
      image = "gcr.io/${var.project_id}/tatvaagroapp_webserver"
      resources {
        limits = {
          cpu    = "1"
          memory = "512Mi"
        }
      }
    }
  }
}

resource "google_sql_database_instance" "mongodb_cluster_external" {
  name             = "mongodb_cluster_external"
  database_version = "POSTGRES_15"
  region           = "us-central1"
  project          = var.project_id

  settings {
    tier = "db-n1-standard-1"
    disk_size = 100

    availability_type = "ZONAL"
  }

  deletion_protection = false
}

# Resource: App Secrets & Environment Variables (secret-manager)
# Add custom Terraform configuration for this GCP component

